// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetCurrentVersion():Promise<string>;

export function GetDesktopState():Promise<Record<string, any>>;

export function GetInstallerPaths():Promise<Record<string, any>>;

export function GetSignatureStatus():Promise<Record<string, any>>;

export function LocalURL():Promise<string>;

export function OpenInstallerFolder():Promise<void>;

export function OpenLocalPage(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RestartLocalServer():Promise<void>;
