// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckForUpdate'](arg1, arg2, arg3);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDesktopState() {
  return window['go']['main']['App']['GetDesktopState']();
}

export function GetInstallerPaths() {
  return window['go']['main']['App']['GetInstallerPaths']();
}

export function GetSignatureStatus() {
  return window['go']['main']['App']['GetSignatureStatus']();
}

export function LocalURL() {
  return window['go']['main']['App']['LocalURL']();
}

export function OpenInstallerFolder() {
  return window['go']['main']['App']['OpenInstallerFolder']();
}

export function OpenLocalPage(arg1) {
  return window['go']['main']['App']['OpenLocalPage'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RestartLocalServer() {
  return window['go']['main']['App']['RestartLocalServer']();
}
